name: dart_analyzer
description: A Dart code analyzer that compiles to JavaScript
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  js: ^0.6.7
  dart_style: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.4
  lints: ^2.1.0
